name: Docker Image CI

on:
  push:
    branches: [ master ]

jobs:

  build:

    runs-on: debian-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: |
        echo "dckr_pat_z5NaIFawkNN1KxxHQWMP2SNzhvg" | docker login -u "dekleor" --password-stdin docker.io
        docker build . --file Dockerfile --tag docker.io/dekleor/psitest:$GITHUB_SHA
        docker push docker.io/$dekleor/psitest:$GITHUB_SHA
